version: '3'

services:
  apollo-quick-start:
    image: registry.docimaxvip.com/base/apollo-docimax:latest
    container_name: apollo-quick-start
    restart: always
    depends_on:
      - mysql
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8070:8070"
    networks:
      - sc_net
      
  keycloak:
    image: registry.docimaxvip.com/base/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: Docimax@123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Docimax@123
      TZ: Asia/Shanghai
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    volumes:
      - ./cert/docimax.crt:/etc/x509/https/tls.crt
      - ./cert/docimax.key:/etc/x509/https/tls.key
    ports:
      - 8443:8443
      - 8442:8080
    depends_on:
      - mysql
    networks:
      - sc_net
        
  redis:
    image: registry.docimaxvip.com/base/redis
    container_name: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    sysctls:
      net.core.somaxconn: 511
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass Docimax@123", "--appendonly", "yes"]
    networks:
      - sc_net
      
  rabbitmq:
    image: registry.docimaxvip.com/base/rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_NODENAME: rabbitmq
    ports:
      - 9419:9419
      - 5672:5672
      - 15672:15672
    networks:
      - sc_net
      
  mysql:
    image: registry.docimaxvip.com/base/mysql:latest
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Docimax@123
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: Docimax@123
    command:
      --max_connections=500
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - sc_net

  xxl-job-admin:
    image: registry.docimaxvip.com/base/xxl-job-admin:latest
    container_name: xxl-job-admin
    restart: always
    ports:
      - 8060:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=Docimax@123"
    volumes:
      - ./data/xxl-job-admin/log:/data/applogs
    depends_on:
      - mysql
    networks:
      - sc_net
      
  xxl-job-executor:
    image: registry.docimaxvip.com/base/xxl-job-executor:latest
    container_name: xxl-job-executor
    restart: always
    ports:
      - 8112:8112
    environment:
      TZ: Asia/Shanghai
      PARAMS: "--server.port=8112 --xxl.job.admin.addresses=http://xxl-job-admin:8080/xxl-job-admin"
    depends_on:
      - xxl-job-admin
    networks:
      - sc_net
      
  auth-web:
    image: registry.docimaxvip.com/common/auth-web:release_1.0-10
    container_name: auth-web
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./cert:/cert
      - ./files/config.js:/usr/share/nginx/html/config.js:ro
      - ./files/auth.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 18880:80
    depends_on:
      - auth
      - keycloak
    networks:
      - sc_net
      
  auth:
    image: registry.docimaxvip.com/common/auth:release_1.0-28
    container_name: auth
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 18881:18881
    depends_on:
      - apollo-quick-start
      - redis
      - keycloak
      - mysql
    networks:
      - sc_net
  
  docimax-gateway:
    image: registry.docimaxvip.com/common/docimax-gateway:release_beijing-22
    container_name: docimax-gateway
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 18883:18883
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sc_net

  minio:
    image: registry.docimaxvip.com/base/minio:2021-10-13
    container_name: minio
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: Docimax@123
      MINIO_SERVER_URL: http://172.30.199.61:9000
    ports:
      - 9000:9000
      - 9002:9001
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio
    command: server  --address ":9000" --console-address ":9001" /data
    networks:
      - sc_net

networks:
  sc_net:
    name: sc_net
